apiVersion: v1
kind: Service
metadata:
  name: python-webserver
  labels:
    run: python-webserver
spec:
  selector:
    run: python-webserver
  #type: LoadBalancer
  ports:
    - protocol: TCP
      name: python-webserver
      port: 8083
      targetPort: containerport